spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/book
    username: book_user
    password: book_password
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE