spring:
  data:
    mongodb:
      port: 27017
      database: book

#mongock:
#  enabled: on
#  change-logs-scan-package:
#    - ru.otus.changelog
#  runner-type: "ApplicationRunner" # default
#  #runner-type: "InitializingBean"
#  mongo-db:
#    write-concern:
#      journal: false
#    read-concern: local
