spring:
  data:
    mongodb:
      port: 0
      database: book
  shell:
    command:
      version:
        enabled: false
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  enabled: on
  change-logs-scan-package:
    - ru.otus.changelog
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
