ALTER TABLE IF EXISTS AUTHOR
    DROP CONSTRAINT IF EXISTS unique_name;
DROP TABLE IF EXISTS AUTHOR CASCADE;

CREATE TABLE AUTHOR
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

ALTER TABLE IF EXISTS GENRE
    DROP CONSTRAINT IF EXISTS unique_name;
DROP TABLE IF EXISTS GENRE CASCADE;
CREATE TABLE GENRE
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

ALTER TABLE GENRE
    ADD CONSTRAINT genre_unique_name UNIQUE (NAME);

ALTER TABLE IF EXISTS BOOK
    DROP CONSTRAINT IF EXISTS FK_AUTHOR;
ALTER TABLE IF EXISTS BOOK
    DROP CONSTRAINT IF EXISTS FK_GENRE;
DROP TABLE IF EXISTS BOOK CASCADE;
CREATE TABLE BOOK
(
    ID        BIGSERIAL PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    CONSTRAINT FK_AUTHOR
        FOREIGN KEY (AUTHOR_ID)
            REFERENCES AUTHOR (ID),
    CONSTRAINT FK_GENRE
        FOREIGN KEY (GENRE_ID)
            REFERENCES GENRE (ID)
);

ALTER TABLE IF EXISTS COMMENT
    DROP CONSTRAINT IF EXISTS FK_BOOK;
DROP TABLE IF EXISTS COMMENT CASCADE;

CREATE TABLE COMMENT
(
    ID      BIGSERIAL PRIMARY KEY,
    TEXT    VARCHAR(65535),
    BOOK_ID BIGINT,
    CONSTRAINT FK_BOOK
        FOREIGN KEY (BOOK_ID)
            REFERENCES BOOK (ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS ROLE CASCADE;
CREATE TABLE ROLE
(
    ID   BIGSERIAL PRIMARY KEY,
    ROLE VARCHAR(65535)
);

DROP TABLE IF EXISTS SYS_USER CASCADE;

CREATE TABLE SYS_USER
(
    ID                      BIGSERIAL PRIMARY KEY,
    USERNAME                VARCHAR(65535) UNIQUE,
    PASSWORD                VARCHAR(65535),
    is_account_non_expired     boolean,
    is_account_non_locked      boolean,
    is_credentials_non_expired boolean,
    is_enabled               boolean
);

DROP TABLE IF EXISTS USER_ROLES CASCADE;

CREATE TABLE USER_ROLES
(
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
            REFERENCES SYS_USER (ID),
    CONSTRAINT FK_ROLE
        FOREIGN KEY (ROLE_ID)
            REFERENCES ROLE (ID)
);