DROP TABLE IF EXISTS AUTHOR CASCADE;

CREATE TABLE AUTHOR
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

ALTER TABLE IF EXISTS GENRE
    DROP CONSTRAINT IF EXISTS genre_unique_name;
DROP TABLE IF EXISTS GENRE CASCADE;
CREATE TABLE GENRE
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

ALTER TABLE GENRE ADD CONSTRAINT genre_unique_name UNIQUE (NAME);

ALTER TABLE IF EXISTS BOOK
    DROP CONSTRAINT IF EXISTS FK_AUTHOR;
ALTER TABLE IF EXISTS BOOK
    DROP CONSTRAINT IF EXISTS FK_GENRE;
DROP TABLE IF EXISTS BOOK CASCADE;
CREATE TABLE BOOK
(
    ID        BIGSERIAL PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    CONSTRAINT FK_AUTHOR
        FOREIGN KEY (AUTHOR_ID)
            REFERENCES AUTHOR (ID),
    CONSTRAINT FK_GENRE
        FOREIGN KEY (GENRE_ID)
            REFERENCES GENRE (ID)
);