version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always

  mongodb-setup:
    image: mongo
    container_name: mongodb-setup
    command: >
      bash -c "sleep 10 && mongo mongodb://mongodb:27017/db-setup /setup.js"
    volumes:
      - ./setup.js:/setup.js
    depends_on:
      - mongodb